import { Providers } from "../redux/provider";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "QR Scanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
